name: App Pipeline

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]
  release:
    types: [ published ]

permissions:
  contents: read
  packages: write
  pull-requests: read

jobs:
  deploy-dev:
    if: |
      (github.event_name == 'pull_request' && github.base_ref == 'dev') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/dev')
    uses: pinokew/shared-workflows/.github/workflows/shared-ci-cd.yml@main
    with:
      environment_name: development
      deploy: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
      use_ansible: false
      build_and_push_docker: false
      docker_image_name: cloudflare-tunnel
    secrets: inherit

  deploy-prod:
    if: |
      (github.event_name == 'pull_request' && github.base_ref == 'main') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'release' && startsWith(github.event.release.tag_name, 'v'))
    uses: pinokew/shared-workflows/.github/workflows/shared-ci-cd.yml@main
    with:
      environment_name: production
      deploy: ${{ github.event_name == 'release' && startsWith(github.event.release.tag_name, 'v') }}
      use_ansible: false
      build_and_push_docker: false
      docker_image_name: cloudflare-tunnel
    secrets: inherit

